services:
  rails:
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    image: jumpseller-api
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - .:/project
      - bundle_data:/bundle
      - $HOME/.ssh:/project/docker/development/home/.ssh
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis_data:/data

# sidekiq:
#   build:
#     dockerfile: docker/development/Dockerfile
#     context: .
#   entrypoint: docker/development/sidekiq-entrypoint
#   env_file:
#     - .env
#   restart: always
#   volumes:
#     - $HOME/.ssh:/project/docker/development/home/.ssh
#     - .:/project
#   depends_on:
#     - redis

volumes:
  bundle_data:
  postgres_data:
  redis_data:
